# Target specific macros
TARGET = sensorsdisplay_OSEK
TARGET_SOURCES = \
	sensorsdisplay.c
TOPPERS_OSEK_OIL_SOURCE = ./sensorsdisplay.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
