// generated by builder.sce: Please do not edit this file
// ------------------------------------------------------
bro_comm_blocks_path=get_absolute_file_path('loader.sce');
link(bro_comm_blocks_path+'libbro_comm_blocks.so',['bro_comm_blocks'],'c');
