# Target specific macros
TARGET = BRO_client2
TARGET_SOURCES := \
	BRO_spam_client.c \
	BRO_spam_fists.c 
TOPPERS_OSEK_OIL_SOURCE := ./BRO_spam_client.oil

O_PATH ?= build

include /home/dacav/Uni/Corsi/Lab-Embedded/nxtOSEK/ecrobot/ecrobot.mak
